name: Build release image

on:
  workflow_dispatch:

jobs:
  build-stable:
    uses: ./.github/workflows/build_and_publish.yml
    with:
      appGitRefs: ${{ vars.VERSION_LB_APP }}
      appAddSha: false
      imgBuild: ${{ vars.VERSION_LB_IMG }}
      regName: ${{ vars.REGISTRY_URL }}
      regLogin: ${{ vars.REGISTRY_LOGIN }}
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
