name: Build and publish on workflow call

on:
  workflow_call:
    inputs:
      appGitRefs:
        required: true
        type: string
      appAddSha:
        required: false
        type: boolean
        default: false
      imgBuild:
        required: true
        type: string
      regName:
        required: true
        type: string
      regLogin:
        required: true
        type: string
    secrets:
      REGISTRY_TOKEN:
        description: docker registry access token
        required: true

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      appTag: ${{ steps.get_meta.outputs.appTag }}
    steps:
      -
        name: Get the docker image metadata
        id: get_meta
        run: |
          appTag=$(basename ${{ inputs.appGitRefs }} | sed -e "s/^[vV]//")
          echo "appTag=$appTag" >> $GITHUB_OUTPUT
  build:
    needs: prepare
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      meta-images: ${{ inputs.regLogin }}/librebooking
      meta-tags: |
        type=raw,value=${{ needs.prepare.outputs.appTag }},suffix=-${{ inputs.imgBuild }}
        type=raw,value=${{ needs.prepare.outputs.appTag }}
    secrets:
      registry-auths: |
        - registry: ${{ inputs.regName }}
          username: ${{ inputs.regLogin }}
          password: ${{ secrets.REGISTRY_TOKEN }}
